const board=document.getElementById('board'),timeEl=document.getElementById('time'),movesEl=document.getElementById('moves'),pairsEl=document.getElementById('pairs'),messageEl=document.getElementById('message'),modal=document.getElementById('modal');
const suits={characters:['一','二','三','四','五','六','七','八','九'],bamboo:['🀐','🀑','🀒','🀓','🀔','🀕','🀖','🀗','🀘'],dots:['●','●','●','●','●','●','●','●','●']};
const honors=[['東','east'],['南','south'],['西','west'],['北','north'],['中','red'],['發','green'],['白','white']];
const special=[['梅','flower'],['蘭','flower'],['菊','flower'],['竹','flower'],['春','season'],['夏','season'],['秋','season'],['冬','season']];
let tiles=[],selected=null,moves=0,pairs=0,startTime=0,timer=null,soundOn=true;
const positions=[];
function addLayer(z,rows,cols,x0,y0,dx=52,dy=68){for(let r=0;r<rows;r++)for(let c=0;c<cols;c++)positions.push({x:x0+c*dx,y:y0+r*dy,z})}
// 144-tile layered layout: 96 + 32 + 12 + 4.
addLayer(0,6,16,84,90,52,68);addLayer(1,4,8,292,158,52,68);addLayer(2,3,4,396,226,52,68);addLayer(3,2,2,448,260,52,68);
const types=[];
for(const suit of ['characters','bamboo','dots'])for(let i=0;i<9;i++)for(let n=0;n<4;n++)types.push({kind:'suited',suit,value:i,label:suit==='characters'?String.fromCharCode(0x4e00+i):suit==='bamboo'?['一','二','三','四','五','六','七','八','九'][i]:String(i+1),glyph:suit==='characters'?String.fromCharCode(0x4e00+i):suit==='bamboo'?suits.bamboo[i]:['●','●','●','●','●','●','●','●','●'][i]});
for(const [glyph,key] of honors)for(let n=0;n<4;n++)types.push({kind:'honor',key,glyph,label:glyph});
for(const [glyph,key] of special)for(let n=0;n<1;n++)types.push({kind:'special',key,glyph,label:glyph});
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function same(a,b){if(a.kind!==b.kind)return false;if(a.kind==='special')return a.key===b.key;if(a.kind==='honor')return a.key===b.key;return a.suit===b.suit&&a.value===b.value}
function makeDeck(){const deck=[...types];while(deck.length<144){const base=types[Math.floor(Math.random()*types.length)];if(base.kind==='special')deck.push({...base});else deck.push({...base});}return shuffle(deck).slice(0,144)}
function overlap(a,b){return a.x<b.x+52&&a.x+52>b.x&&a.y<b.y+68&&a.y+68>b.y}
function isFree(t){const above=tiles.some(o=>!o.removed&&o.z>t.z&&overlap(t,o));if(above)return false;const left=tiles.some(o=>!o.removed&&o.z===t.z&&o.x<t.x&&o.x+52>t.x-3&&Math.abs(o.y-t.y)<20);const right=tiles.some(o=>!o.removed&&o.z===t.z&&o.x>t.x&&o.x<t.x+55&&Math.abs(o.y-t.y)<20);return !left||!right}
function canPair(a,b){return same(a.data,b.data)}
function render(){board.innerHTML='';tiles.forEach(t=>{if(t.removed)return;const el=document.createElement('button');el.className='tile '+(isFree(t)?'free':'blocked')+(selected===t?' selected':'');el.style.left=t.x+'px';el.style.top=t.y+'px';el.style.zIndex=t.z*200+t.order;el.setAttribute('aria-label',`${t.data.label} tile${isFree(t)?', open':''}`);const glyph=document.createElement('span');glyph.className='glyph';glyph.textContent=t.data.glyph;el.appendChild(glyph);const small=document.createElement('span');small.className='small';small.textContent=t.data.kind==='suited'?(t.data.suit==='characters'?'萬':t.data.suit==='bamboo'?'索':'筒'):t.data.key==='special'?'':t.data.kind==='honor'?'字':'';el.appendChild(small);el.onclick=()=>clickTile(t);board.appendChild(el)})}
function clickTile(t){if(!isFree(t)){flash('That tile is blocked.');return}if(selected===t){selected=null;render();return}if(!selected){selected=t;render();return}if(canPair(selected,t)){const a=selected,b=t;selected=null;a.removed=b.removed=true;moves++;pairs++;update();render();beep(620,.07);if(pairs===72)finish(true);else if(!tiles.some(t=>!t.removed&&isFree(t))){setTimeout(()=>{flash('No open tiles left — shuffle to continue.');},100)}}else{selected=t;flash('Those tiles do not match.');render();beep(180,.08)}}
function update(){movesEl.textContent=moves;pairsEl.textContent=`${pairs} / 72`}
function flash(text){messageEl.textContent=text;messageEl.classList.remove('hidden');clearTimeout(flash.t);flash.t=setTimeout(()=>messageEl.classList.add('hidden'),1300)}
function formatTime(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function tick(){timeEl.textContent=formatTime(Math.floor((Date.now()-startTime)/1000))}
function start(){clearInterval(timer);startTime=Date.now();timer=setInterval(tick,1000);moves=0;pairs=0;selected=null;update();tiles=makeDeck().map((data,i)=>({...positions[i],data,order:i,removed:false}));render();modal.classList.add('hidden');timeEl.textContent='00:00'}
function finish(won){clearInterval(timer);document.getElementById('finalTime').textContent=timeEl.textContent;document.getElementById('finalMoves').textContent=moves;document.getElementById('modalTitle').textContent=won?'Beautifully done.':'Keep going.';document.getElementById('modalCopy').textContent=won?`You cleared all 144 tiles in ${timeEl.textContent}, with ${moves} moves.`:'The board is out of moves. Shuffle the remaining tiles or start fresh.';modal.classList.remove('hidden')}
function shuffleRemaining(){const active=tiles.filter(t=>!t.removed);shuffle(active);active.forEach((t,i)=>{t.data=active[i].data});selected=null;render();flash('Remaining tiles shuffled.')} 
function hint(){const free=tiles.filter(t=>!t.removed&&isFree(t));for(let i=0;i<free.length;i++)for(let j=i+1;j<free.length;j++)if(canPair(free[i],free[j])){selected=free[i];render();setTimeout(()=>{selected=free[j];render();setTimeout(()=>{selected=null;render()},650)},650);return}flash('No matching open pair found. Shuffle to continue.')}
function beep(freq,dur){if(!soundOn)return;try{const c=new (window.AudioContext||window.webkitAudioContext)();const o=c.createOscillator(),g=c.createGain();o.frequency.value=freq;o.type='sine';g.gain.value=.025;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+dur)}catch(e){}}
document.getElementById('newGame').onclick=start;document.getElementById('playAgain').onclick=start;document.getElementById('shuffle').onclick=shuffleRemaining;document.getElementById('hint').onclick=hint;document.getElementById('soundBtn').onclick=()=>{soundOn=!soundOn;document.getElementById('soundBtn').textContent=soundOn?'🔊':'🔇'};document.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='h')hint();if(e.key==='Escape'){selected=null;render()}});start();